### DISCUSSION TITLE
Backend-Entwicklung

### DISCUSSION THREAD

**Discussion by Phape** [Phape/smart-security#18] [General]
Idee:
- Grafana für die UI
- InfluxDB für die Datenhaltung
- PahoMQTT (benötigt?) als Receiver
- Mosquitto als MQTT Server / Broker (bereits umgesetzt, derzeit noch im entsprechenden Branch)

Mögliche docker-compose.yml (von [dzone](https://dzone.com/articles/playing-with-docker-mqtt-grafana-influxdb-python-a)):
``` yaml
version: '2'

services:
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    container_name: moquitto
    ports:
     - "9001:9001"
     - "1883:1883"
    restart: always

  influxdb:
    image: hypriot/rpi-influxdb
    container_name: influxdb
    restart: always
    environment:
     - INFLUXDB_INIT_PWD="password"
     - PRE_CREATE_DB="iot"
    ports:
     - "8083:8083"
     - "8086:8086"
    volumes:
     - ~/docker/rpi-influxdb/data:/data

  grafana:
    image: fg2it/grafana-armhf:v4.6.3
    container_name: grafana
    restart: always
    ports:
     - "3000:3000"
    volumes:
      - grafana-db:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-conf:/etc/grafana

volumes:
  grafana-db:
    driver: local  
  grafana-log:
    driver: local
  grafana-conf:
    driver: local
```

**Comment by Phape** [comment]
[MariaDB Docker](https://hub.docker.com/_/mariadb/)
docker-compose.yml:
``` yaml
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
